fix

diff --git a/liblkars b/liblkars
--- a/liblkars
+++ b/liblkars
@@ -28,6 +28,7 @@ fi
 
 
 LKARS="$HOME/.local"
+
 #Download source files
 get_bin()
 {
@@ -61,45 +62,41 @@ luma_display()
 # Build Frame Buffer copy (fbcp)
 build_pirate_audio_fbcp()
 {
-  ( git --version || sudo apt install git )
-  ( [ ! -d "$LKARS/src/fbcp/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
-  ( [ ! -f /usr/bin/cmake ] && sudo apt install cmake -y ) || ( echo "cmake installed" )
-#( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DST7735SW=ON -DGPIO_TFT_BACKLIGHT=16 -DGPIO_TFT_RESET_PIN=21 -DGPIO_TFT_DATA_CONTROL=20 -DSPI_BUS_CLOCK_DIVISOR=30 -DSTATISTICS=0 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=OFF .. )
-#( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DST7735R=ON -DGPIO_TFT_BACKLIGHT=16 -DGPIO_TFT_RESET_PIN=21 -DGPIO_TFT_DATA_CONTROL=20 -DSPI_BUS_CLOCK_DIVISOR=30 -DSTATISTICS=0 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=OFF .. )
-  ( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DPIRATE_AUDIO_ST7789_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=30 -DBACKLIGHT_CONTROL=ON -DUSE_DMA_TRANSFERS=OFF -DSTATISTICS=0 .. )
-#( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DWAVESHARE_ST7789VW_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=30 -DBACKLIGHT_CONTROL=ON -DUSE_DMA_TRANSFERS=OFF -DSTATISTICS=0 .. )
-  ( cd "$LKARS/src/fbcp/build/" && make -j )
-  ( [ -f "$LKARS/src/fbcp/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$LKARS/src/fbcp/build/fbcp-ili9341" "/usr/bin/fbcp" || echo "error cp bin/fbcp" )
+( git --version || sudo apt install git )
+( [ ! -d "$FBCP/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$FBCP" || echo "pass" )
+( [ -d "$FBCP/" ] && mkdir "$FBCP/build" ) && ( cd "$FBCP/build/" && cmake -Wno-dev -DPIRATE_AUDIO_ST7789_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=30 -DBACKLIGHT_CONTROL=ON -DUSE_DMA_TRANSFERS=OFF -DSTATISTICS=0 .. )
+( cd "$FBCP/build/" && make -j )
+( [ -f "$FBCP/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$FBCP/build/fbcp-ili9341" "/usr/bin/fbcp" || echo "error cp /bin/fbcp" )
 }
 
 build_st7735sw_fbcp()
 {
   ( git --version || sudo apt install git )
-  ( [ ! -d "$LKARS/src/fbcp/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
+  ( [ ! -d "$FBCP/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
   ( [ ! -f /usr/bin/cmake ] && sudo apt install cmake -y ) || ( echo "cmake installed" )
-  ( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DST7735SW=ON -DGPIO_TFT_BACKLIGHT=16 -DGPIO_TFT_RESET_PIN=21 -DGPIO_TFT_DATA_CONTROL=20 -DSPI_BUS_CLOCK_DIVISOR=30 -DSTATISTICS=0 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=OFF .. )
-  ( cd "$LKARS/src/fbcp/build/" && make -j )
-  ( [ -f "$LKARS/src/fbcp/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$LKARS/src/fbcp/build/fbcp-ili9341" "/usr/bin/fbcp" || echo "error cp bin/fbcp" )
+  ( [ -d "$FBCP/" ] && mkdir "$FBCP/build" ) && ( cd "$FBCP/build/" && cmake -Wno-dev -DST7735SW=ON -DGPIO_TFT_BACKLIGHT=16 -DGPIO_TFT_RESET_PIN=21 -DGPIO_TFT_DATA_CONTROL=20 -DSPI_BUS_CLOCK_DIVISOR=30 -DSTATISTICS=0 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=OFF .. )
+  ( cd "$FBCP/build/" && make -j )
+  ( [ -f "$FBCP/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$FBCP/build/fbcp-ili9341" "/usr/bin/fbcp" || echo "error cp bin/fbcp" )
 }
 
 build_st7735r_fbcp()
 {
   ( git --version || sudo apt install git )
-  ( [ ! -d "$LKARS/src/fbcp/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
+  ( [ ! -d "$FBCP/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
   ( [ ! -f /usr/bin/cmake ] && sudo apt install cmake -y ) || ( echo "cmake installed" )
-  ( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DST7735R=ON -DGPIO_TFT_BACKLIGHT=16 -DGPIO_TFT_RESET_PIN=21 -DGPIO_TFT_DATA_CONTROL=20 -DSPI_BUS_CLOCK_DIVISOR=30 -DSTATISTICS=0 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=OFF .. )
-  ( cd "$LKARS/src/fbcp/build/" && make -j )
-  ( [ -f "$LKARS/src/fbcp/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$LKARS/src/fbcp/build/fbcp-ili9341" "/usr/bin/fbcp" || echo "error cp bin/fbcp" )
+  ( [ -d "$FBCP/" ] && mkdir "$FBCP/build" ) && ( cd "$FBCP/build/" && cmake -Wno-dev -DST7735R=ON -DGPIO_TFT_BACKLIGHT=16 -DGPIO_TFT_RESET_PIN=21 -DGPIO_TFT_DATA_CONTROL=20 -DSPI_BUS_CLOCK_DIVISOR=30 -DSTATISTICS=0 -DDISPLAY_SWAP_BGR=ON -DDISPLAY_INVERT_COLORS=OFF .. )
+  ( cd "$FBCP/build/" && make -j )
+  ( [ -f "$FBCP/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$FBCP/build/fbcp-ili9341" "/usr/bin/fbcp" || echo "error cp bin/fbcp" )
 }
 
 build_waveshare_fbcp()
 {
   ( git --version || sudo apt install git )
-  ( [ ! -d "$LKARS/src/fbcp/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
+  ( [ ! -d "$FBCP/" ] && git clone https://github.com/Tearran/fbcp-ili9341.git  "$LKARS/src/fbcp" || echo "pass" )
   ( [ ! -f /usr/bin/cmake ] && sudo apt install cmake -y ) || ( echo "cmake installed" )
-  ( [ -d "$LKARS/src/fbcp/" ] && mkdir "$LKARS/src/fbcp/build" ) && ( cd "$LKARS/src/fbcp/build/" && cmake -Wno-dev -DWAVESHARE_ST7789VW_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=30 -DBACKLIGHT_CONTROL=ON -DUSE_DMA_TRANSFERS=OFF -DSTATISTICS=0 .. )
-  ( cd "$LKARS/src/fbcp/build/" && make -j )
-  ( [ -f "$LKARS/src/fbcp/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$LKARS/src/fbcp/build/fbcp-ili9341" "/bin/fbcp" || echo "error cp /bin/fbcp" )
+  ( [ -d "$FBCP/" ] && mkdir "$FBCP/build" ) && ( cd "$FBCP/build/" && cmake -Wno-dev -DWAVESHARE_ST7789VW_HAT=ON -DSPI_BUS_CLOCK_DIVISOR=30 -DBACKLIGHT_CONTROL=ON -DUSE_DMA_TRANSFERS=OFF -DSTATISTICS=0 .. )
+  ( cd "$FBCP/build/" && make -j )
+  ( [ -f "$FBCP/build/fbcp-ili9341" ] || echo "error building fbcp" ) && (  sudo cp "$FBCP/build/fbcp-ili9341" "/bin/fbcp" || echo "error cp /bin/fbcp" )
 }
 
 fbcpd_systemctl()
@@ -190,25 +187,18 @@ echo "Restore Complete!"
 
 240x240_bootconfig()
 {
-cat << OSEOF > $LKARS/src/lkars/config.txt
-display_rotate=1
-hdmi_group=2
-hdmi_mode=87
-hdmi_cvt=240 240 60 1 0 0 0
-hdmi_force_hotplug=1
+cat << OSEOF > "$FBCP/build/config.txt"
+# Additional overlays and parameters are documented /boot/overlays/README
 
-# Uncomment some or all of these to enable the optional hardware interfaces
+disable_overscan=1
 dtparam=i2c_arm=on
 dtparam=i2s=on
-#dtparam=spi=off
-
-
+dtparam=spi=off
+# Enable audio (DAC)
+dtparam=audio=off
 dtoverlay=hifiberry-dac
 gpio=25=op,dh
 
-# Additional overlays and parameters are documented /boot/overlays/README
-# Enable audio (loads snd_bcm2835)
-dtparam=audio=off
 [pi4]
 # Enable DRM VC4 V3D driver on top of the dispmanx display stack
 dtoverlay=vc4-fkms-v3d
@@ -216,20 +206,26 @@ max_framebuffers=2
 
 [all]
 #dtoverlay=vc4-fkms-v3d
+display_rotate=1
+hdmi_group=2
+hdmi_mode=87
+hdmi_cvt=240 240 60 1 0 0 0
+hdmi_force_hotplug=1
 
 OSEOF
 
 sudo cp --no-preserve=mode -f /boot/config.txt /boot/config.bak
-echo "Back up exitsing config"
-sudo cp --no-preserve=mode -f "$LKARS/src/lkars/config.txt" /boot/config.txt
-echo "Restore Complete!"
+echo "Back up exitsing config.txt to config.bak"
+sudo cp --no-preserve=mode -f "$FBCP/build/config.txt" /boot/config.txt
+echo "240x240 Display set!"
+echo "sudo fbcp&"
 
 }
 
 128x160_bootconfig()
 {
 cd "$LKARS/" || exit
-cat << OSEOF > "$LKARS/src/lkars/config.txt"
+cat << OSEOF > "$FBCP/build/config.txt"
 # Enable audio (loads snd_bcm2835)
 dtparam=audio=off
 #Remove black border
@@ -249,7 +245,7 @@ OSEOF
 
 sudo cp --no-preserve=mode -f /boot/config.txt /boot/old.config
 echo "Back up exitsing config"
-sudo cp --no-preserve=mode -f "$LKARS/src/lkars/config.txt" /boot/config.txt
+sudo cp --no-preserve=mode -f "$FBCP/build/config.txt" /boot/config.txt
 echo "Framebuffer copy, Configuration complete!"
 
 }
@@ -263,6 +259,7 @@ sudo nano /etc/samba/smb.conf
 echo "enter a password"
 sudo smbpasswd -a alpha
 sudo service smbd restart
+
 }
 
 rem_samba()
@@ -270,8 +267,6 @@ rem_samba()
 sudo apt-get purge samba
 sudo rm -rf /etc/samba/ /etc/default/samba
 }
-#!/bin/bash
-
 
 use_iic()
 {
