Update lkars-config

diff --git a/lkars-config b/lkars-config
--- a/lkars-config
+++ b/lkars-config
@@ -1,16 +1,18 @@
 #!/bin/bash
 # lkars-config
-clear
 
-( [ -f /usr/lib/liblkars.0 ]  && source "/usr/lib/liblkars.0" ) || echo "liblkars.0 NOT found"
+clear
+source "/usr/lib/liblkars.0"
+[ ! -f /usr/lib/liblkars.0 ]  &&   echo "liblkars.0 NOT found"
 
 
 menu_main(){
-  menu=("1" "Display" 2 "Apps" "0" "Reboot")
-  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Finish  --menu "Make your choice" 16 100 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
+  menu=("1" "Install App" "2" "Check Sensors" "9" "Development" "0" "Reboot")
+  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Finish  --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
     case $CHOICE in
-        "1") menu_display ;;
-        "2") menu_apps ;;   
+        "1") menu_apps ;;
+        "2") [ -f /usr/bin/iic-get ] && iic-get 1 ;;
+        "9") menu_dev ;;
         "0") sudo reboot ;;
          *) exit ;;
     esac
@@ -18,7 +20,18 @@ menu_main(){
 
 menu_display(){
   menu=("1" "ST7735SW" "2" "Pirate audio phat" "3" "Restore System Default")
-  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 16 100 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
+  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
+      case "$CHOICE" in
+        "1") build_st7735sw_fbcp && 128x160_bootconfig && fbcpd_systemctl;;
+        "2") build_pirate_audio_fbcp && 240x240_bootconfig && fbcpd_systemctl ;;
+        "3") default_bootconfig && ( sudo systemctl disable fbcpd ) ;;
+      esac
+      return 0
+}
+
+menu_dev(){
+  menu=("1" "ST7735SW" "2" "Pirate audio phat" "3" "Restore System Default")
+  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
       case "$CHOICE" in
         "1") build_st7735sw_fbcp && 128x160_bootconfig && fbcpd_systemctl;;
         "2") build_pirate_audio_fbcp && 240x240_bootconfig && fbcpd_systemctl ;;
@@ -29,7 +42,7 @@ menu_display(){
 
 menu_apps(){
   menu=("1" "Download Source" "2" "Virtual environment" "3" "Samba file share")
-  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 16 100 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
+  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
 
       case "$CHOICE" in
         "1") get_src ;;
@@ -39,6 +52,17 @@ menu_apps(){
       return 0
 }
 
+menu_samba(){
+  menu=("1" "Download Source" "2" "Virtual environment" "3" "Samba file share")
+  CHOICE=$( whiptail --title "LKARS Systems" --cancel-button Back --menu "Make your choice" 25 50 9 "${menu[@]}"  3>&2 2>&1 1>&3 )
+
+      case "$CHOICE" in
+        "1") get_src ;;
+        "2") set_vertenv ;;
+        "3") set_samba ;;
+      esac
+      return 0
+}
 while true ;
  do
    menu_main
